2022-01-10 14:51:43,947 INFO    MainThread:2249718 [wandb_setup.py:_flush():71] setting env: {}
2022-01-10 14:51:43,947 INFO    MainThread:2249718 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-10 14:51:43,947 INFO    MainThread:2249718 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-10 14:51:43,947 INFO    MainThread:2249718 [wandb_init.py:_log_setup():371] Logging user logs to /mnt/nfs/rdata02-users/users/makaroff/UNet_pytorch/wandb/run-20220110_145143-uxhcgosz/logs/debug.log
2022-01-10 14:51:43,948 INFO    MainThread:2249718 [wandb_init.py:_log_setup():372] Logging internal logs to /mnt/nfs/rdata02-users/users/makaroff/UNet_pytorch/wandb/run-20220110_145143-uxhcgosz/logs/debug-internal.log
2022-01-10 14:51:43,948 INFO    MainThread:2249718 [wandb_init.py:init():404] calling init triggers
2022-01-10 14:51:43,948 INFO    MainThread:2249718 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-01-10 14:51:43,948 INFO    MainThread:2249718 [wandb_init.py:init():460] starting backend
2022-01-10 14:51:43,948 INFO    MainThread:2249718 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-10 14:51:43,958 INFO    MainThread:2249718 [backend.py:ensure_launched():216] starting backend process...
2022-01-10 14:51:43,964 INFO    MainThread:2249718 [backend.py:ensure_launched():221] started backend process with pid: 2249771
2022-01-10 14:51:43,976 INFO    MainThread:2249718 [wandb_init.py:init():469] backend started and connected
2022-01-10 14:51:43,980 INFO    MainThread:2249718 [wandb_init.py:init():533] updated telemetry
2022-01-10 14:51:43,990 INFO    MainThread:2249718 [wandb_init.py:init():563] communicating current version
2022-01-10 14:51:44,652 INFO    MainThread:2249718 [wandb_init.py:init():568] got version response 
2022-01-10 14:51:44,652 INFO    MainThread:2249718 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-10 14:51:44,830 INFO    MainThread:2249718 [wandb_init.py:init():606] starting run threads in backend
2022-01-10 14:51:44,886 INFO    MainThread:2249718 [wandb_run.py:_console_start():1810] atexit reg
2022-01-10 14:51:44,887 INFO    MainThread:2249718 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-01-10 14:51:44,888 INFO    MainThread:2249718 [wandb_run.py:_redirect():1689] Redirecting console.
2022-01-10 14:51:44,890 INFO    MainThread:2249718 [wandb_run.py:_redirect():1745] Redirects installed.
2022-01-10 14:51:44,890 INFO    MainThread:2249718 [wandb_init.py:init():633] run started, returning control to user process
2022-01-10 14:53:47,367 INFO    MainThread:2249718 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 1
2022-01-10 14:53:47,369 INFO    MainThread:2249718 [wandb_run.py:_restore():1752] restore
2022-01-10 14:53:49,816 INFO    MainThread:2249718 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 463
  total_bytes: 463
}

2022-01-10 14:53:50,070 INFO    MainThread:2249718 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 463
  total_bytes: 463
}

2022-01-10 14:53:51,006 INFO    MainThread:2249718 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 463
  total_bytes: 14162
}

2022-01-10 14:53:51,107 INFO    MainThread:2249718 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 463
  total_bytes: 14483
}

2022-01-10 14:53:51,209 INFO    MainThread:2249718 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 14134
  total_bytes: 14483
}

2022-01-10 14:53:51,310 INFO    MainThread:2249718 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 14483
  total_bytes: 14483
}

2022-01-10 14:53:51,412 INFO    MainThread:2249718 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 14483
  total_bytes: 14483
}

2022-01-10 14:53:51,514 INFO    MainThread:2249718 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 14483
  total_bytes: 14483
}

2022-01-10 14:53:51,616 INFO    MainThread:2249718 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 14483
  total_bytes: 14483
}

2022-01-10 14:53:52,183 INFO    MainThread:2249718 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 14483
  total_bytes: 14483
}

2022-01-10 14:53:52,594 INFO    MainThread:2249718 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 14483
  total_bytes: 14483
}
local_info {
}

2022-01-10 14:53:53,676 INFO    MainThread:2249718 [wandb_run.py:_append_files():2180] logging synced files
